apiVersion: v1
kind: Service
metadata:
  name: extldap
  namespace: default
spec:
  ports:
    - port: 389
---
apiVersion: v1
kind: Endpoints
metadata:
  name: extldap
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.99.7
    ports:
      - port: 389


