apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  clusterIP:
  externalIPs: 
  - 192.168.99.50
  ports:
  - name: http
    port: 5601
    targetPort: http
  type: NodePort
