apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: web
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: httpd
        image: docker.io/httpd:latest
        ports:
        - containerPort: 80


