version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /docker/registry
http:
  addr: :5000
  host: https://jake1.local1.site
  secret: myregistrysecret0123456789
  tls:
    certificate: /certs/jake1cert.pem
    key: /certs/jake1key.pem
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
