apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnfs-1
spec:
  capacity:
     storage: 3Gi
  accessModes: 
     - ReadWriteOnce
     - ReadWriteMany
     - ReadOnlyMany
  nfs:
     path: "/data/share1"
     server: 192.168.99.7
  persistentVolumeReclaimPolicy: Recycle
 
