apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnfs-2
spec:
  capacity:
     storage: 3Gi
  accessModes: 
     - ReadWriteOnce
     - ReadWriteMany
     - ReadOnlyMany
  nfs:
     path: "/data/share2"
     server: 192.168.99.7
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: nfs-claim-prebind

 
