apiVersion: v1
kind: Pod
metadata:
  name: init-demo-1
spec:
  initContainers:
  - name: install
    image: busybox
    command:
    - wget
    - "-O"
    - "/my-content-dir/index.html"
    - http://kubernetes.io
    volumeMounts:
    - name: contentdir
      mountPath: "/my-content-dir"
  containers:
  - name: nginx
    image: docker.io/nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: contentdir
      mountPath: /usr/share/nginx/html
  dnsPolicy: Default
  volumes:
  - name: contentdir
    emptyDir: {}

