apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: docker.io/busybox:1.28
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster; nslookup gcr.io
          restartPolicy: OnFailure
