apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: mlb-default
      protocol: layer2
      addresses:
      - 192.168.99.100-192.168.99.105

