apiVersion: v1
kind: Service
metadata:
  name: ngx
  annotations:
    metallb.universe.tf/address-pool: mlb-default
spec:
  loadBalancerIP: 192.168.99.105
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ngx
  type: LoadBalancer
