apiVersion: v1
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: object-counts
    namespace: k8limited
  spec:
      hard:
        persistentvolumeclaims: "4"
        services.loadbalancers: "7"
        services.nodeports: "1"
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: storagequota
    namespace: k8limited
  spec:
      hard:
        persistentvolumeclaims: "5"
        requests.storage: "5Gi"
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: storagelimits
    namespace: k8limited
  spec:
    limits:
     - type: PersistentVolumeClaim
       max:
          storage: 2Gi
       min:
          storage: 1Gi
kind: List
