apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnfs
spec:
  capacity:
     storage: 1Gi
  accessModes: 
     - ReadWriteOnce
     - ReadWriteMany
     - ReadOnlyMany
  nfs:
     path: "/data/nfsshare"
     server: 192.168.99.12
  persistentVolumeReclaimPolicy: Retain
 
