apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  containers:
  - name: count
    image: docker.io/centos:latest
    command: [bash, -c]
    args: ['for ((i=0;;i++));do echo "$i:$(date)";sleep 1;done']

