apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: high
value: 1000000
globalDefault: false
description: "Prio Class High for Special Pods."
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: low
value: 5000
globalDefault: false
description: "Prio Low for normal Pods."

