apiVersion: v1
kind: Pod
metadata:
  name: webpod
  labels:
    app: webpod
spec:
  containers:
    - name: httpd
      image: docker.io/httpd:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
    - name: client
      image: docker.io/centos:latest
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash","-c","while true; do curl http://localhost:80; sleep 5; done"]

