apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: "192.168.99.7"
networking:
  podSubnet: 10.0.0.0/12
kubeProxy:
  config:
    featureGates:
      SupportIPVSProxyMode: true
    mode: "ipvs"

