apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
api:
  advertiseAddress: "192.168.99.7"
kubeProxy:
  config:
    featureGates:
      SupportIPVSProxyMode: true
    mode: "ipvs"
controllerManagerExtraArgs:
  horizontal-pod-autoscaler-use-rest-clients: "false"
