kind: Pod
apiVersion: v1
metadata:
  name: write-pod
spec:
#  nodeSelector:
#    kubernetes.io/hostname: elwood1.local1.site
  containers:
  - name: write-pod
    image: docker.io/busybox:1.28
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: nfs
