apiVersion: v1
kind: Pod
metadata:
  name: exec-live-ready-check
spec:
  containers:
  - name: exec-live-ready-check
    image: docker.io/httpd:latest
    readinessProbe:
      exec:
        command: ["/bin/bash","-c","pidof httpd-xyz"]
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
    ports:
    - containerPort: 80

