apiVersion: v1
kind: Pod
metadata:
  name: http-live-check
spec:
  containers:
  - name: http-live-check
    image: docker.io/httpd:latest
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      timeoutSeconds: 5
    ports:
    - containerPort: 80

