apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterblock
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
         storage: 1G
  storageClassName: glusterfs-storage-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs
spec:
  accessModes:
   - ReadWriteMany
  resources:
    requests:
         storage: 1G
  storageClassName: glusterfs-storage


